"""removendo o campo telefone

Revision ID: 426211639d02
Revises: 623faeff46f2
Create Date: 2026-09-04 14:11:29.410157

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '426211639d02'
down_revision = '623faeff46f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('telefone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefone', mysql.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
