"""criando campo telefone

Revision ID: 623faeff46f2
Revises: 6088e1e5c67c
Create Date: 2026-09-02 17:44:01.127822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '623faeff46f2'
down_revision = '6088e1e5c67c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefone', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('telefone')

    # ### end Alembic commands ###
